### ISSUE TITLE
[Request] - Please make a port of this theme for VsCode

### ISSUE THREAD

**Issue by cloudUser98** [kvrohit/mellow.nvim#11]
I really love this color theme, i was a neo vim user but for personal reasons i moved back to VsCode, i tried to find a color theme that resembles this one but sadly there's none, i wish to be able to use this color theme in my vsCode environment.

**Comment by kvrohit** [comment]
Well, I did not have any plans to support vscode until this point. Let me see what I can do.

**Comment by kvrohit** [comment]
I have started work on the port to VSCode, however the progress is slow. Hopefully it will be done in a week's time.

**Comment by kvrohit** [comment]
@cloudUser98 Theme published: https://marketplace.visualstudio.com/items?itemName=kvrohit.mellow-theme.

Repo: https://github.com/kvrohit/mellow-theme. Please file any bug reports or enhancements there. Thanks!

**Comment by cloudUser98** [comment]
> @cloudUser98 Theme published: https://marketplace.visualstudio.com/items?itemName=kvrohit.mellow-theme.
> 
> Repo: https://github.com/kvrohit/mellow-theme. Please file any bug reports or enhancements there. Thanks!

Already using it, love it!
