### ISSUE TITLE
[Request] Git Delta theme

### ISSUE THREAD

**Issue by andreafspeziale** [kvrohit/mellow.nvim#15]
Really love this palette, thank you for your work! 🙏 
Wouldn't be awesome to have it also as GitDelta theme?

Ref: https://github.com/dandavison/delta/blob/master/themes.gitconfig

**Comment by kvrohit** [comment]
@andreafspeziale Glad you like it! Will look into adding the support for git-delta.

**Comment by kvrohit** [comment]
Created a PR: https://github.com/dandavison/delta/pull/1452

**Comment by kvrohit** [comment]
@andreafspeziale the PR was merged thanks to the project maintainers. You can use this theme in your config now after you have downloaded the latest `theme.gitconfig` from delta's repo. Feedback appreciated.

**Comment by andreafspeziale** [comment]
Wow thats awesome, thanks for your work!
