### ISSUE TITLE
hop.nvim integration?

### ISSUE THREAD

**Issue by nexxeln** [kvrohit/mellow.nvim#3]
Absolutely love the theme! Are there any chances you could add a [hop.nvim](https://github.com/phaazon/hop.nvim) integration?

**Comment by kvrohit** [comment]
Thank you! `hop.nvim` integration has been added to the `develop` branch. As I do not use it myself, I would love to have you try it and give some feedback. You can pull this change by specifying the branch in your packer config:

```lua
use({ "kvrohit/mellow.nvim", branch = "develop" })
```

**Comment by nexxeln** [comment]
That looks really nice! You can merge it

**Comment by kvrohit** [comment]
Merged! Thanks for the feedback.
