### ISSUE TITLE
Transparent mode doesn't work. 

### ISSUE THREAD

**Issue by stoykotolev** [kvrohit/mellow.nvim#8]
I tried enabling transparent mode for the theme, with the following `colorscheme.lua` config:

```
vim.g.mellow_transparent = true
vim.g.mellow_italic_functions = true
vim.g.mellow_bold_functions = true

vim.cmd [[colorscheme mellow]]
```

Howerver my terminal is still not transparent
![image](https://user-images.githubusercontent.com/63452072/208524943-acf5b9c4-0ead-414a-9100-ced33f60a7d8.png)

Here is my nvim configuration:
![Screenshot 2022-12-19 at 11 15 00 PM](https://user-images.githubusercontent.com/63452072/208525384-24c16f74-38ab-43c2-9b0e-5f2b31d714c1.png)

Am I missing something here?

**Comment by kvrohit** [comment]
Probably a bug. On it.

**Comment by kvrohit** [comment]
Should be fixed now.

**Comment by stoykotolev** [comment]
Yeah, it works great now. Thanks!
